Add PDF support to Android standalone view

diff --git a/pdfjs/build b/pdfjs/build
--- a/pdfjs/build
+++ b/pdfjs/build
@@ -2,7 +2,7 @@
 set -e
 
 if [[ -z $PDFJS_CONFIG ]]; then
-	echo "Error: PDFJS_CONFIG is not set. Use one of: zotero, web, dev, all" >&2
+	echo "Error: PDFJS_CONFIG is not set. Use one of: zotero, web, dev, mobile, all" >&2
 	exit 1
 fi
 
@@ -27,6 +27,26 @@ popd
 if [[ $PDFJS_CONFIG = "dev" || $PDFJS_CONFIG = "all" ]]; then
 	# Set up directories for dev build
 	BUILD=dev
+	BUILD_DIR="$BUILD_BASE/$BUILD/pdf"
+	rm -rf "$BUILD_DIR"
+	mkdir -p "$BUILD_DIR/build"
+	mkdir -p "$BUILD_DIR/web/images"
+	cp -r "$PDFJS_BUILD/LICENSE" "$BUILD_DIR/"
+	cp -r "$PDFJS_BUILD/build/pdf.mjs" "$BUILD_DIR/build/"
+	cp -r "$PDFJS_BUILD/build/pdf.worker.mjs" "$BUILD_DIR/build/"
+	cp -r "$PDFJS_BUILD/web/cmaps" "$BUILD_DIR/web/"
+	cp -r "$PDFJS_BUILD/web/standard_fonts" "$BUILD_DIR/web/"
+	cp -r "$PDFJS_BUILD/web/iccs" "$BUILD_DIR/web/"
+	cp -r "$PDFJS_BUILD/web/wasm" "$BUILD_DIR/web/"
+	cp -r "$PDFJS_BUILD/web/viewer.html" "$BUILD_DIR/web/"
+	cp -r "$PDFJS_BUILD/web/viewer.mjs" "$BUILD_DIR/web/"
+	cp -r "$PDFJS_BUILD/web/images/loading-icon.gif" "$BUILD_DIR/web/images/"
+	cp -r "pdfjs/viewer.css" "$BUILD_DIR/web/"
+fi
+
+if [[ $PDFJS_CONFIG = "mobile" || $PDFJS_CONFIG = "all" ]]; then
+	# Set up directories for mobile build
+	BUILD=mobile
 	BUILD_DIR="$BUILD_BASE/$BUILD/pdf"
 	rm -rf "$BUILD_DIR"
 	mkdir -p "$BUILD_DIR/build"
